### PR TITLE
Update 10174.txt

### PR DESCRIPTION
**Pull request by vvasuki**
I'd be contributing more frequent fixes if the formatting decision were set right.

### CODE REVIEW

**Comment by drdhaval2785** [comment]
If you intend to submit frequent fixes, preferred way would be to create a PR at sanskrit-lexicon/csl-orig repo. That would make life easier.

**Comment by vvasuki** [comment]
Prefer devanAgarI. Also, if better formatting is not allowed, I mostly would ignore errors.

**Comment by drdhaval2785** [comment]
In that case csl-devanagari repository is the best place. You can generate PR there. I will fetch it to csl-orig.

**Comment by drdhaval2785** [comment]
https://github.com/sanskrit-lexicon/csl-devanagari is the repository where you can submit corrections via PR in Devanagari.
Regarding your formatting issues, discussions are going on at https://github.com/sanskrit-lexicon/COLOGNE/issues/419 to drop line breaks and have a better textual representation. Should be through soon.

**Comment by drdhaval2785** [comment]
Correction made in the above commit. Should be available on Cologne within a week or so.

**Pull request closed without merging**
